from __future__ import annotations
from PySide6.QtCore import QObject,Signal
TRANSLATIONS={
"ko":{"app_title":"Music Wave Studio","media":"음원","reference":"참고 파형","templates":"파형 스타일","playlist":"예약 작업","audio":"음악 반응","design":"디자인","effects":"효과","export":"저장 설정","add_audio":"음원 추가","add_folder":"폴더 추가","analyze":"음원 분석","play":"재생","pause":"일시정지","stop":"정지","render":"지금 만들기","queue_add":"대기열에 추가","queue_start":"예약 작업 모두 시작","validate":"음원 검사","system":"환경 검사","cancel":"작업 중지","ready":"준비됨","advanced":"고급 설정","simple":"간편 모드","step1":"1. 음원 폴더","step2":"2. 파형 선택","step3":"3. 미리보기","step4":"4. 대기열","step5":"5. 시작","movement":"움직임 크기","response":"반응 속도","smooth":"움직임 부드러움","glow":"빛 번짐","bass":"저음 반응","treble":"고음 반응","capcut_alpha":"CapCut용 투명 파형","capcut_screen":"CapCut Screen용","quality_alpha":"최고 품질 투명","queue_count":"예약 작업 {count} / 5","set_ready":"준비 완료","set_waiting":"대기","set_running":"처리 중","set_done":"완료","set_failed":"오류","first_title":"Music Wave Studio에 오신 것을 환영합니다.","first_body":"1. 음원을 넣습니다.\\n2. 파형 스타일을 고릅니다.\\n3. 미리봅니다.\\n4. 저장 형식을 고릅니다.\\n5. 만들기를 누릅니다."},
"en":{"app_title":"Music Wave Studio","media":"Media","reference":"Reference","templates":"Templates","playlist":"Queue","audio":"Audio Response","design":"Design","effects":"Effects","export":"Export","add_audio":"Add Audio","add_folder":"Add Folder","analyze":"Analyze Audio","play":"Play","pause":"Pause","stop":"Stop","render":"Create Now","queue_add":"Add to Queue","queue_start":"Start All Queued","validate":"Validate Audio","system":"System Check","cancel":"Cancel","ready":"Ready","advanced":"Advanced Settings","simple":"Simple Mode","step1":"1. Audio Folder","step2":"2. Choose Style","step3":"3. Preview","step4":"4. Queue","step5":"5. Start","movement":"Movement","response":"Response","smooth":"Smoothness","glow":"Glow","bass":"Bass","treble":"Highs","capcut_alpha":"Transparent Waveform for CapCut","capcut_screen":"MP4 Screen Blend for CapCut","quality_alpha":"Highest Quality Transparent","queue_count":"Queued Jobs {count} / 5","set_ready":"Ready","set_waiting":"Waiting","set_running":"Running","set_done":"Done","set_failed":"Failed","first_title":"Welcome to Music Wave Studio","first_body":"1. Add your audio.\\n2. Choose a waveform style.\\n3. Preview it.\\n4. Choose an export format.\\n5. Create your video."}}
class Translator(QObject):
    languageChanged=Signal(str)
    def __init__(self,language="ko"):super().__init__();self.language=language if language in TRANSLATIONS else "ko"
    def set_language(self,language):
        self.language=language if language in TRANSLATIONS else "ko";self.languageChanged.emit(self.language)
    def tr(self,key,**kwargs):return TRANSLATIONS[self.language].get(key,key).format(**kwargs)
